name: Build and deploy to GitHub Pages
on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix profile install nixpkgs#python312Packages.pygments
      - run: nix build
      - name: Rebuild and Sync webmentions
        env:
          WMTOKEN: pbj7jHLLhU_iUTPiavjsPg
        run: ./result/bin/site rebuild -v

      - name: Commit webmentions to repository
        env:
          COMMIT_MSG: |
            Sync webmentions
        run: |
          git config user.email "maxfiialkovskyi@protonmais.com"
          git config user.name "maxfii"
          git add webmentions.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin test)

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
